<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup><ItemGroup><ProjectReference Include="../Trippify.Application/Trippify.Application.csproj" /><PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11"><PrivateAssets>all</PrivateAssets></PackageReference><PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" /><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" /></ItemGroup></Project>
