<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup><ItemGroup><ProjectReference Include="../Trippify.Application/Trippify.Application.csproj"/><ProjectReference Include="../Trippify.Infrastructure/Trippify.Infrastructure.csproj"/><PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1"/><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11"><PrivateAssets>all</PrivateAssets></PackageReference></ItemGroup></Project>
